#include "core/DefaultNetworks.h"

#include <QStringList>

#include <utility>

namespace maxchat::core {

namespace {

maxchat::irc::ServerEndpoint makeEndpoint(QString host, int port, bool tls) {
    maxchat::irc::ServerEndpoint endpoint;
    endpoint.host = std::move(host);
    endpoint.port = port;
    endpoint.tls = tls;
    return endpoint;
}

} // namespace

QList<NetworkDefaults> defaultNetworks() {
    return {
        {
            QStringLiteral("Libera.Chat"),
            makeEndpoint(QStringLiteral("irc.libera.chat"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://libera.chat/"),
            {makeEndpoint(QStringLiteral("irc.libera.chat"), 6667, false)},
        },
        {
            QStringLiteral("Freenode"),
            makeEndpoint(QStringLiteral("irc.freenode.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://freenode.net/"),
            {makeEndpoint(QStringLiteral("chat.freenode.net"), 6667, false)},
        },
        {
            QStringLiteral("OFTC"),
            makeEndpoint(QStringLiteral("irc.oftc.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.oftc.net/"),
            {},
        },
        {
            QStringLiteral("Rizon"),
            makeEndpoint(QStringLiteral("irc.rizon.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://rizon.net/"),
            {makeEndpoint(QStringLiteral("irc.rizon.ca"), 6697, true),
             makeEndpoint(QStringLiteral("irc.rizon.no"), 6697, true),
             makeEndpoint(QStringLiteral("rizon.c.datapacket.com"), 6697, true)},
        },
        {
            QStringLiteral("DALnet"),
            makeEndpoint(QStringLiteral("irc.dal.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.dal.net/"),
            {makeEndpoint(QStringLiteral("ix.dal.net"), 6697, true),
             makeEndpoint(QStringLiteral("pool.dal.net"), 6697, true),
             makeEndpoint(QStringLiteral("underworld.se.eu.dal.net"), 6697, true)},
        },
        {
            QStringLiteral("IRCnet"),
            makeEndpoint(QStringLiteral("open.ircnet.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.ircnet.com/"),
            {makeEndpoint(QStringLiteral("ssl.ircnet.ovh"), 6697, true),
             makeEndpoint(QStringLiteral("ssl.cloak.ircnet.ovh"), 6697, true)},
        },
        {
            QStringLiteral("Quakenet"),
            makeEndpoint(QStringLiteral("irc.quakenet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.quakenet.org/"),
            {makeEndpoint(QStringLiteral("adrift.sg.quakenet.org"), 6667, false),
             makeEndpoint(QStringLiteral("atw.hu.quakenet.org"), 6667, false),
             makeEndpoint(QStringLiteral("cymru.us.quakenet.org"), 6667, false),
             makeEndpoint(QStringLiteral("euroserv.fr.quakenet.org"), 6667, false),
             makeEndpoint(QStringLiteral("hostsailor.ro.quakenet.org"), 6667, false),
             makeEndpoint(QStringLiteral("stockholm.se.quakenet.org"), 6667, false),
             makeEndpoint(QStringLiteral("tngnet.nl.quakenet.org"), 6667, false),
             makeEndpoint(QStringLiteral("underworld2.no.quakenet.org"), 6667, false)},
        },
        {
            QStringLiteral("Undernet"),
            makeEndpoint(QStringLiteral("irc.undernet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.undernet.org/"),
            {makeEndpoint(QStringLiteral("chicago.il.us.undernet.org"), 6667, false),
             makeEndpoint(QStringLiteral("bucharest.ro.eu.undernet.org"), 6667, false),
             makeEndpoint(QStringLiteral("budapest.hu.eu.undernet.org"), 6667, false),
             makeEndpoint(QStringLiteral("dallas.tx.us.undernet.org"), 6667, false),
             makeEndpoint(QStringLiteral("losangeles.ca.us.undernet.org"), 6667, false),
             makeEndpoint(QStringLiteral("miami.fl.us.undernet.org"), 6667, false)},
        },
        {
            QStringLiteral("EFnet"),
            makeEndpoint(QStringLiteral("irc.efnet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.efnet.org/"),
            {makeEndpoint(QStringLiteral("irc.choopa.net"), 6697, true),
             makeEndpoint(QStringLiteral("efnet.deic.eu"), 6697, true),
             makeEndpoint(QStringLiteral("efnet.port80.se"), 6697, true),
             makeEndpoint(QStringLiteral("irc.underworld.no"), 6697, true)},
        },
        {
            QStringLiteral("Snoonet"),
            makeEndpoint(QStringLiteral("irc.snoonet.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://snoonet.org/"),
            {},
        },
        {
            QStringLiteral("SwiftIRC"),
            makeEndpoint(QStringLiteral("irc.swiftirc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.swiftirc.net/"),
            {},
        },
        {
            QStringLiteral("2600net"),
            makeEndpoint(QStringLiteral("irc.scuttled.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.2600.net/"),
            {},
        },
        {
            QStringLiteral("Abjects"),
            makeEndpoint(QStringLiteral("irc.abjects.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://abjects.net/"),
            {},
        },
        {
            QStringLiteral("AfterNET"),
            makeEndpoint(QStringLiteral("irc.afternet.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.afternet.org/"),
            {},
        },
        {
            QStringLiteral("Aitvaras"),
            makeEndpoint(QStringLiteral("irc.data.lt"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://data.lt/"),
            {},
        },
        {
            QStringLiteral("AllNetwork"),
            makeEndpoint(QStringLiteral("irc.allnetwork.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://allnetwork.org/"),
            {},
        },
        {
            QStringLiteral("AlphaChat"),
            makeEndpoint(QStringLiteral("irc.alphachat.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://alphachat.net/"),
            {},
        },
        {
            QStringLiteral("Atrum"),
            makeEndpoint(QStringLiteral("irc.atrum.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://atrum.org/"),
            {},
        },
        {
            QStringLiteral("AustNet"),
            makeEndpoint(QStringLiteral("irc.austnet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.austnet.org/"),
            {},
        },
        {
            QStringLiteral("Axon"),
            makeEndpoint(QStringLiteral("irc.axon.pw"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://axon.pw/"),
            {},
        },
        {
            QStringLiteral("AyoChat"),
            makeEndpoint(QStringLiteral("irc.ayochat.or.id"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://or.id/"),
            {},
        },
        {
            QStringLiteral("Azzurra"),
            makeEndpoint(QStringLiteral("irc.azzurra.chat"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.azzurra.org/"),
            {},
        },
        {
            QStringLiteral("Beyondirc"),
            makeEndpoint(QStringLiteral("irc.beyondirc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://beyondirc.net/"),
            {},
        },
        {
            QStringLiteral("BOLChat"),
            makeEndpoint(QStringLiteral("irc.bolchat.com"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://bolchat.com/"),
            {},
        },
        {
            QStringLiteral("Bongster"),
            makeEndpoint(QStringLiteral("ssl.bongster.de"), 9666, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://bongster.de/"),
            {},
        },
        {
            QStringLiteral("BrasIRC"),
            makeEndpoint(QStringLiteral("irc.brasirc.com.br"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://com.br/"),
            {},
        },
        {
            QStringLiteral("CanterNet"),
            makeEndpoint(QStringLiteral("irc.canternet.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://canternet.org/"),
            {},
        },
        {
            QStringLiteral("Chat4all"),
            makeEndpoint(QStringLiteral("irc.chat4all.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.chat4all.org/"),
            {},
        },
        {
            QStringLiteral("ChatSpike"),
            makeEndpoint(QStringLiteral("irc.chatspike.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.chatspike.net/"),
            {},
        },
        {
            QStringLiteral("ChatZona"),
            makeEndpoint(QStringLiteral("irc.chatzona.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://chatzona.org/"),
            {},
        },
        {
            QStringLiteral("CnCIRC"),
            makeEndpoint(QStringLiteral("irc.cncirc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://cncirc.net/"),
            {},
        },
        {
            QStringLiteral("Coolsmile"),
            makeEndpoint(QStringLiteral("irc.coolsmile.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://coolsmile.net/"),
            {},
        },
        {
            QStringLiteral("DareNET"),
            makeEndpoint(QStringLiteral("irc.darenet.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.darenet.org/"),
            {},
        },
        {
            QStringLiteral("Dark-Tou-Net"),
            makeEndpoint(QStringLiteral("irc.d-t-net.de"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://d-t-net.de/"),
            {},
        },
        {
            QStringLiteral("darkfasel.net"),
            makeEndpoint(QStringLiteral("irc.darkfasel.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://darkfasel.net/"),
            {},
        },
        {
            QStringLiteral("DarkMyst"),
            makeEndpoint(QStringLiteral("irc.darkmyst.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.darkmyst.org/"),
            {},
        },
        {
            QStringLiteral("darkscience"),
            makeEndpoint(QStringLiteral("irc.darkscience.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://darkscience.net/"),
            {},
        },
        {
            QStringLiteral("Darkworld"),
            makeEndpoint(QStringLiteral("irc.darkworld.network"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://darkworld.network/"),
            {},
        },
        {
            QStringLiteral("DejaToons"),
            makeEndpoint(QStringLiteral("irc.dejatoons.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.dejatoons.net/"),
            {},
        },
        {
            QStringLiteral("DesireNET"),
            makeEndpoint(QStringLiteral("irc.desirenet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://desirenet.org/"),
            {},
        },
        {
            QStringLiteral("ECNet"),
            makeEndpoint(QStringLiteral("irc.ecnet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://ecnet.org/"),
            {},
        },
        {
            QStringLiteral("EpiKnet"),
            makeEndpoint(QStringLiteral("irc.epiknet.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://epiknet.org/"),
            {},
        },
        {
            QStringLiteral("EsperNet"),
            makeEndpoint(QStringLiteral("irc.esper.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.esper.net/"),
            {},
        },
        {
            QStringLiteral("euIRCnet"),
            makeEndpoint(QStringLiteral("irc.euirc.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.euirc.net/"),
            {},
        },
        {
            QStringLiteral("EuropNet"),
            makeEndpoint(QStringLiteral("irc.europnet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://europnet.org/"),
            {},
        },
        {
            QStringLiteral("Evolu.NET"),
            makeEndpoint(QStringLiteral("irc.evolu.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://evolu.net/"),
            {},
        },
        {
            QStringLiteral("ExplosionIRC"),
            makeEndpoint(QStringLiteral("irc.explosionirc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://explosionirc.net/"),
            {},
        },
        {
            QStringLiteral("FDFnet"),
            makeEndpoint(QStringLiteral("irc.fdfnet.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://fdfnet.net/"),
            {},
        },
        {
            QStringLiteral("FEFnet"),
            makeEndpoint(QStringLiteral("irc.fef.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://fef.net/"),
            {},
        },
        {
            QStringLiteral("Financialchat"),
            makeEndpoint(QStringLiteral("irc.financialchat.com"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://financialchat.com/"),
            {},
        },
        {
            QStringLiteral("Forestnet"),
            makeEndpoint(QStringLiteral("irc.forestnet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://forestnet.org/"),
            {},
        },
        {
            QStringLiteral("FreeUniBG"),
            makeEndpoint(QStringLiteral("irc.FreeUniBG.eu"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://freeunibg.eu/"),
            {},
        },
        {
            QStringLiteral("GameSurge"),
            makeEndpoint(QStringLiteral("irc.gamesurge.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.gamesurge.net/"),
            {},
        },
        {
            QStringLiteral("GeekNode"),
            makeEndpoint(QStringLiteral("irc.geeknode.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.geeknode.org/"),
            {},
        },
        {
            QStringLiteral("GeekShed"),
            makeEndpoint(QStringLiteral("irc.geekshed.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.geekshed.net/"),
            {},
        },
        {
            QStringLiteral("German-Elite"),
            makeEndpoint(QStringLiteral("irc.german-elite.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://german-elite.net/"),
            {},
        },
        {
            QStringLiteral("GigaIRC"),
            makeEndpoint(QStringLiteral("irc.gigairc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://gigairc.net/"),
            {},
        },
        {
            QStringLiteral("GIMPNet"),
            makeEndpoint(QStringLiteral("irc.gimp.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.gimp.org/"),
            {},
        },
        {
            QStringLiteral("GlobalGamers"),
            makeEndpoint(QStringLiteral("irc.globalgamers.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://globalgamers.net/"),
            {},
        },
        {
            QStringLiteral("GoodChatting"),
            makeEndpoint(QStringLiteral("irc.goodchatting.com"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://goodchatting.com/"),
            {},
        },
        {
            QStringLiteral("hackint"),
            makeEndpoint(QStringLiteral("irc.hackint.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://hackint.org/"),
            {},
        },
        {
            QStringLiteral("HybridIRC"),
            makeEndpoint(QStringLiteral("irc.hybridirc.com"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://hybridirc.com/"),
            {},
        },
        {
            QStringLiteral("ICQ-Chat"),
            makeEndpoint(QStringLiteral("irc.icq-chat.com"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://icq-chat.com/"),
            {},
        },
        {
            QStringLiteral("Immortal-Anime"),
            makeEndpoint(QStringLiteral("irc.immortal-anime.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://immortal-anime.net/"),
            {},
        },
        {
            QStringLiteral("Indymedia"),
            makeEndpoint(QStringLiteral("irc.indymedia.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.indymedia.org/"),
            {},
        },
        {
            QStringLiteral("IRC-Hispano"),
            makeEndpoint(QStringLiteral("irc.irc-hispano.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.irc-hispano.org/"),
            {},
        },
        {
            QStringLiteral("IRC2"),
            makeEndpoint(QStringLiteral("irc.irc2.hu"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://irc2.hu/"),
            {},
        },
        {
            QStringLiteral("IRC4Fun"),
            makeEndpoint(QStringLiteral("irc.irc4fun.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://irc4fun.net/"),
            {},
        },
        {
            QStringLiteral("IRCGate.it"),
            makeEndpoint(QStringLiteral("irc.ircgate.it"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://ircgate.it/"),
            {},
        },
        {
            QStringLiteral("IRCHighway"),
            makeEndpoint(QStringLiteral("irc.irchighway.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.irchighway.net/"),
            {},
        },
        {
            QStringLiteral("IRCsource"),
            makeEndpoint(QStringLiteral("irc.ircsource.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://ircsource.net/"),
            {},
        },
        {
            QStringLiteral("IRCtoo"),
            makeEndpoint(QStringLiteral("irc.irctoo.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://irctoo.net/"),
            {},
        },
        {
            QStringLiteral("IRCube"),
            makeEndpoint(QStringLiteral("irc.ircube.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://ircube.org/"),
            {},
        },
        {
            QStringLiteral("IrcWorld"),
            makeEndpoint(QStringLiteral("irc.ircworld.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://ircworld.org/"),
            {},
        },
        {
            QStringLiteral("IRDSI"),
            makeEndpoint(QStringLiteral("irc.irdsi.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://irdsi.net/"),
            {},
        },
        {
            QStringLiteral("KampungChat"),
            makeEndpoint(QStringLiteral("irc.kampungchat.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://kampungchat.org/"),
            {},
        },
        {
            QStringLiteral("KnightIRC"),
            makeEndpoint(QStringLiteral("irc.knightirc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://knightirc.net/"),
            {},
        },
        {
            QStringLiteral("Kreynet"),
            makeEndpoint(QStringLiteral("irc.krey.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://krey.net/"),
            {},
        },
        {
            QStringLiteral("Krono"),
            makeEndpoint(QStringLiteral("irc.krono.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://krono.net/"),
            {},
        },
        {
            QStringLiteral("LibraIRC"),
            makeEndpoint(QStringLiteral("irc.librairc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.librairc.net/"),
            {},
        },
        {
            QStringLiteral("LichtSnel"),
            makeEndpoint(QStringLiteral("irc.lichtsnel.nl"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://lichtsnel.nl/"),
            {},
        },
        {
            QStringLiteral("LinkNet"),
            makeEndpoint(QStringLiteral("irc.link-net.be"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.link-net.org/"),
            {},
        },
        {
            QStringLiteral("Luatic"),
            makeEndpoint(QStringLiteral("irc.luatic.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://luatic.net/"),
            {},
        },
        {
            QStringLiteral("Maddshark"),
            makeEndpoint(QStringLiteral("irc.maddshark.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://maddshark.net/"),
            {},
        },
        {
            QStringLiteral("MagicStar"),
            makeEndpoint(QStringLiteral("irc.magicstar.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://magicstar.net/"),
            {},
        },
        {
            QStringLiteral("MagNET"),
            makeEndpoint(QStringLiteral("irc.perl.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.irc.perl.org/"),
            {},
        },
        {
            QStringLiteral("Mibbit"),
            makeEndpoint(QStringLiteral("irc.mibbit.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://mibbit.net/"),
            {},
        },
        {
            QStringLiteral("MindForge"),
            makeEndpoint(QStringLiteral("irc.mindforge.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://mindforge.org/"),
            {},
        },
        {
            QStringLiteral("NationCHAT"),
            makeEndpoint(QStringLiteral("irc.nationchat.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://nationchat.org/"),
            {},
        },
        {
            QStringLiteral("NightStar"),
            makeEndpoint(QStringLiteral("irc.nightstar.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://nightstar.net/"),
            {},
        },
        {
            QStringLiteral("NullIRC"),
            makeEndpoint(QStringLiteral("irc.nullirc.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://nullirc.net/"),
            {},
        },
        {
            QStringLiteral("OltreIrc"),
            makeEndpoint(QStringLiteral("irc.oltreirc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://oltreirc.net/"),
            {},
        },
        {
            QStringLiteral("OpenJoke"),
            makeEndpoint(QStringLiteral("irc.openjoke.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://openjoke.org/"),
            {},
        },
        {
            QStringLiteral("OptiLan"),
            makeEndpoint(QStringLiteral("irc.lt-tech.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://lt-tech.org/"),
            {},
        },
        {
            QStringLiteral("Orixon"),
            makeEndpoint(QStringLiteral("irc.orixon.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.orixon.org/"),
            {},
        },
        {
            QStringLiteral("OzOrg"),
            makeEndpoint(QStringLiteral("irc.oz.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.oz.org/"),
            {},
        },
        {
            QStringLiteral("P2P-NET"),
            makeEndpoint(QStringLiteral("irc.p2p-network.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://p2p-network.net/"),
            {},
        },
        {
            QStringLiteral("PhatNET"),
            makeEndpoint(QStringLiteral("irc.phat-net.de"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://phat-net.de/"),
            {},
        },
        {
            QStringLiteral("PIK"),
            makeEndpoint(QStringLiteral("irc.krstarica.com"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.krstarica.com/"),
            {},
        },
        {
            QStringLiteral("PIRC"),
            makeEndpoint(QStringLiteral("irc.pirc.pl"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://pirc.pl/"),
            {},
        },
        {
            QStringLiteral("PTnet"),
            makeEndpoint(QStringLiteral("irc.ptnet.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.ptnet.org/"),
            {},
        },
        {
            QStringLiteral("Recycled-IRC"),
            makeEndpoint(QStringLiteral("irc.recycled-irc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://recycled-irc.net/"),
            {},
        },
        {
            QStringLiteral("RetroNode"),
            makeEndpoint(QStringLiteral("irc.retroit.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://retroit.org/"),
            {},
        },
        {
            QStringLiteral("Rezosup"),
            makeEndpoint(QStringLiteral("irc.rezosup.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://rezosup.org/"),
            {},
        },
        {
            QStringLiteral("RusNet"),
            makeEndpoint(QStringLiteral("irc.rusnet.org.ru"), 6668, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.rusnet.org/"),
            {},
        },
        {
            QStringLiteral("ScaryNet"),
            makeEndpoint(QStringLiteral("irc.scarynet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://scarynet.org/"),
            {},
        },
        {
            QStringLiteral("Serenity-IRC"),
            makeEndpoint(QStringLiteral("irc.serenity-irc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://serenity-irc.net/"),
            {},
        },
        {
            QStringLiteral("ShadowFire"),
            makeEndpoint(QStringLiteral("irc.shadowfire.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://shadowfire.org/"),
            {},
        },
        {
            QStringLiteral("ShadowWorld"),
            makeEndpoint(QStringLiteral("irc.shadowworld.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://shadowworld.net/"),
            {},
        },
        {
            QStringLiteral("SimosNap"),
            makeEndpoint(QStringLiteral("irc.simosnap.com"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://simosnap.com/"),
            {},
        },
        {
            QStringLiteral("SkyChatz"),
            makeEndpoint(QStringLiteral("irc.SkyChatz.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://skychatz.org/"),
            {},
        },
        {
            QStringLiteral("Skyrock"),
            makeEndpoint(QStringLiteral("irc.skyrock.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://skyrock.net/"),
            {},
        },
        {
            QStringLiteral("Slacknet"),
            makeEndpoint(QStringLiteral("irc.slacknet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://slacknet.org/"),
            {},
        },
        {
            QStringLiteral("Slashnet"),
            makeEndpoint(QStringLiteral("irc.slashnet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.slashnet.org/"),
            {},
        },
        {
            QStringLiteral("smurfnet"),
            makeEndpoint(QStringLiteral("irc.smurfnet.ch"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://smurfnet.ch/"),
            {},
        },
        {
            QStringLiteral("SorceryNet"),
            makeEndpoint(QStringLiteral("irc.sorcery.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.sorcery.net/"),
            {},
        },
        {
            QStringLiteral("SpotChat"),
            makeEndpoint(QStringLiteral("irc.spotchat.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.spotchat.org/"),
            {},
        },
        {
            QStringLiteral("ST-City"),
            makeEndpoint(QStringLiteral("irc.st-city.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://st-city.net/"),
            {},
        },
        {
            QStringLiteral("Starlink-irc"),
            makeEndpoint(QStringLiteral("irc.starlink-irc.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://starlink-irc.org/"),
            {},
        },
        {
            QStringLiteral("StarLink.Org"),
            makeEndpoint(QStringLiteral("irc.starlink.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://starlink.org/"),
            {},
        },
        {
            QStringLiteral("StayNet"),
            makeEndpoint(QStringLiteral("irc.staynet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://staynet.org/"),
            {},
        },
        {
            QStringLiteral("StormBit"),
            makeEndpoint(QStringLiteral("irc.stormbit.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.stormbit.net/"),
            {},
        },
        {
            QStringLiteral("synIRC"),
            makeEndpoint(QStringLiteral("irc.synirc.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.synirc.net/"),
            {},
        },
        {
            QStringLiteral("TechNet"),
            makeEndpoint(QStringLiteral("irc.technet.chat"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://technet.chat/"),
            {},
        },
        {
            QStringLiteral("tilde.chat"),
            makeEndpoint(QStringLiteral("irc.tilde.chat"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://tilde.chat/"),
            {},
        },
        {
            QStringLiteral("Tweakers"),
            makeEndpoint(QStringLiteral("irc.tweakers.net"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://tweakers.net/"),
            {},
        },
        {
            QStringLiteral("UnderMind"),
            makeEndpoint(QStringLiteral("irc.undermind.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://undermind.net/"),
            {},
        },
        {
            QStringLiteral("WeNet"),
            makeEndpoint(QStringLiteral("irc.wenet.ru"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://wenet.ru/"),
            {},
        },
        {
            QStringLiteral("WhatNet"),
            makeEndpoint(QStringLiteral("irc.whatnet.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://whatnet.org/"),
            {},
        },
        {
            QStringLiteral("WixChat"),
            makeEndpoint(QStringLiteral("irc.wixchat.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://wixchat.org/"),
            {},
        },
        {
            QStringLiteral("WorldIRC"),
            makeEndpoint(QStringLiteral("irc.worldirc.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://worldirc.org/"),
            {},
        },
        {
            QStringLiteral("Xertion"),
            makeEndpoint(QStringLiteral("irc.xertion.org"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.xertion.org/"),
            {},
        },
        {
            QStringLiteral("Xevion"),
            makeEndpoint(QStringLiteral("irc.xevion.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://xevion.net/"),
            {},
        },
        {
            QStringLiteral("NewNet"),
            makeEndpoint(QStringLiteral("club.newnet.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://newnet.net/"),
            {makeEndpoint(QStringLiteral("tildeclub.newnet.net"), 6667, false),
             makeEndpoint(QStringLiteral("uswest.newnet.net"), 6667, false)},
        },
        {
            QStringLiteral("RelicNet"),
            makeEndpoint(QStringLiteral("irc.relic.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://relic.net/"),
            {},
        },
        {
            QStringLiteral("amigaworld"),
            makeEndpoint(QStringLiteral("irc.amigaworld.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://amigaworld.net/"),
            {makeEndpoint(QStringLiteral("91.213.203.192"), 6667, false)},
        },
        {
            QStringLiteral("ScoutLink"),
            makeEndpoint(QStringLiteral("webchat-ircd.scoutlink.net"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://www.scoutlink.net/"),
            {makeEndpoint(QStringLiteral("clovehitch.scoutlink.net"), 6667, false),
             makeEndpoint(QStringLiteral("birch2.scoutlink.net"), 6667, false)},
        },
        {
            QStringLiteral("BlafaselNet"),
            makeEndpoint(QStringLiteral("irc.blafasel.de"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://blafasel.de/"),
            {makeEndpoint(QStringLiteral("space.blafasel.de"), 6667, false)},
        },
        {
            QStringLiteral("GRnet"),
            makeEndpoint(QStringLiteral("rea.irc.gr"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://grnet.wordpress.com/about/grnet-servers/"),
            {makeEndpoint(QStringLiteral("blue.ircn.gr"), 6667, false),
             makeEndpoint(QStringLiteral("eos.ircn.gr"), 6667, false)},
        },
        {
            QStringLiteral("UniBG"),
            makeEndpoint(QStringLiteral("irc.unibg.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://unibg.org/"),
            {makeEndpoint(QStringLiteral("irc.rosal.bg"), 6667, false)},
        },
        {
            QStringLiteral("Wunder-Nett"),
            makeEndpoint(QStringLiteral("irc.wunder-nett.org"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://wunder-nett.org/"),
            {},
        },
        {
            QStringLiteral("Zeolia"),
            makeEndpoint(QStringLiteral("irc.zeolia.chat"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://zeolia.chat/"),
            {makeEndpoint(QStringLiteral("bds.zeolia.chat"), 6667, false),
             makeEndpoint(QStringLiteral("avalon.zeolia.chat"), 6667, false)},
        },
        {
            QStringLiteral("PureIRC"),
            makeEndpoint(QStringLiteral("irc.pureirc.com"), 6697, true),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://pureirc.com/"),
            {makeEndpoint(QStringLiteral("irc.pureirc.us"), 6697, true),
             makeEndpoint(QStringLiteral("irc.sg.pureirc.us"), 6697, true),
             makeEndpoint(QStringLiteral("irc.nl.pureirc.us"), 6697, true)},
        },
        {
            QStringLiteral("Communiti-Chat"),
            makeEndpoint(QStringLiteral("atrium.communiti.chat"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://communiti.chat/"),
            {},
        },
        {
            QStringLiteral("TeapotChat"),
            makeEndpoint(QStringLiteral("cardamom.teapot.chat"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://teapot.chat/"),
            {makeEndpoint(QStringLiteral("earlgrey.teapot.chat"), 6667, false)},
        },
        {
            QStringLiteral("WebIRC"),
            makeEndpoint(QStringLiteral("webirc.chat"), 6667, false),
            QStringLiteral("comicfan"),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral(""),
            QStringLiteral("https://webirc.chat/"),
            {},
        },
    };
}

QList<maxchat::irc::ServerEndpoint> allServers(const NetworkDefaults& network) {
    QList<maxchat::irc::ServerEndpoint> servers;
    servers.reserve(network.failovers.size() + 1);
    servers.append(network.primary);
    servers.append(network.failovers);
    return servers;
}

maxchat::irc::ServerEndpoint parseServerSpec(const QString& spec, int defaultPort,
                                             bool defaultTls) {
    QString host = spec.trimmed();
    int port = defaultPort;
    bool tls = defaultTls;

    const int colon = host.lastIndexOf(QLatin1Char(':'));
    if (colon > 0 && colon + 1 < host.size()) {
        QString portText = host.mid(colon + 1).trimmed();
        host = host.left(colon).trimmed();
        if (portText.startsWith(QLatin1Char('+'))) {
            tls = true;
            portText.remove(0, 1);
        } else {
            tls = false;
        }
        bool ok = false;
        const int parsedPort = portText.toInt(&ok);
        if (ok) {
            port = parsedPort;
        }
    }

    return makeEndpoint(host, port, tls);
}

QString serverSpec(const maxchat::irc::ServerEndpoint& server) {
    return QStringLiteral("%1:%2%3").arg(server.host, server.tls ? QStringLiteral("+") : QString(),
                                         QString::number(server.port));
}

} // namespace maxchat::core
