"""Default IRC network list — the address book new installs start with.

Server data is curated from mIRC's bundled server list, IRCHelp network pages,
Netsplit network/server listings, and a small set of manually reviewed additions.
The first server for each network is the primary; extra servers are failover.
Users set their own nick per network.
"""

from __future__ import annotations

DEFAULT_NETWORKS: list[dict] = [
    {'name': 'Libera.Chat', 'host': 'irc.libera.chat', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://libera.chat/', 'servers': ['irc.libera.chat:6667']},
    {'name': 'Freenode', 'host': 'irc.freenode.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://freenode.net/', 'servers': ['chat.freenode.net:6667']},
    {'name': 'OFTC', 'host': 'irc.oftc.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.oftc.net/', 'servers': []},
    {'name': 'Rizon', 'host': 'irc.rizon.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://rizon.net/', 'servers': ['irc.rizon.ca:+6697', 'irc.rizon.no:+6697', 'rizon.c.datapacket.com:+6697']},
    {'name': 'DALnet', 'host': 'irc.dal.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.dal.net/', 'servers': ['ix.dal.net:+6697', 'pool.dal.net:+6697', 'underworld.se.eu.dal.net:+6697']},
    {'name': 'IRCnet', 'host': 'open.ircnet.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.ircnet.com/', 'servers': ['ssl.ircnet.ovh:+6697', 'ssl.cloak.ircnet.ovh:+6697']},
    {'name': 'Quakenet', 'host': 'irc.quakenet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.quakenet.org/', 'servers': ['adrift.sg.quakenet.org:6667', 'atw.hu.quakenet.org:6667', 'cymru.us.quakenet.org:6667', 'euroserv.fr.quakenet.org:6667', 'hostsailor.ro.quakenet.org:6667', 'stockholm.se.quakenet.org:6667', 'tngnet.nl.quakenet.org:6667', 'underworld2.no.quakenet.org:6667']},
    {'name': 'Undernet', 'host': 'irc.undernet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.undernet.org/', 'servers': ['chicago.il.us.undernet.org:6667', 'bucharest.ro.eu.undernet.org:6667', 'budapest.hu.eu.undernet.org:6667', 'dallas.tx.us.undernet.org:6667', 'losangeles.ca.us.undernet.org:6667', 'miami.fl.us.undernet.org:6667']},
    {'name': 'EFnet', 'host': 'irc.efnet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.efnet.org/', 'servers': ['irc.choopa.net:+6697', 'efnet.deic.eu:+6697', 'efnet.port80.se:+6697', 'irc.underworld.no:+6697']},
    {'name': 'Snoonet', 'host': 'irc.snoonet.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://snoonet.org/', 'servers': []},
    {'name': 'SwiftIRC', 'host': 'irc.swiftirc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.swiftirc.net/', 'servers': []},
    {'name': '2600net', 'host': 'irc.scuttled.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.2600.net/', 'servers': []},
    {'name': 'Abjects', 'host': 'irc.abjects.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://abjects.net/', 'servers': []},
    {'name': 'AfterNET', 'host': 'irc.afternet.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.afternet.org/', 'servers': []},
    {'name': 'Aitvaras', 'host': 'irc.data.lt', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://data.lt/', 'servers': []},
    {'name': 'AllNetwork', 'host': 'irc.allnetwork.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://allnetwork.org/', 'servers': []},
    {'name': 'AlphaChat', 'host': 'irc.alphachat.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://alphachat.net/', 'servers': []},
    {'name': 'Atrum', 'host': 'irc.atrum.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://atrum.org/', 'servers': []},
    {'name': 'AustNet', 'host': 'irc.austnet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.austnet.org/', 'servers': []},
    {'name': 'Axon', 'host': 'irc.axon.pw', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://axon.pw/', 'servers': []},
    {'name': 'AyoChat', 'host': 'irc.ayochat.or.id', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://or.id/', 'servers': []},
    {'name': 'Azzurra', 'host': 'irc.azzurra.chat', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.azzurra.org/', 'servers': []},
    {'name': 'Beyondirc', 'host': 'irc.beyondirc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://beyondirc.net/', 'servers': []},
    {'name': 'BOLChat', 'host': 'irc.bolchat.com', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://bolchat.com/', 'servers': []},
    {'name': 'Bongster', 'host': 'ssl.bongster.de', 'port': 9666, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://bongster.de/', 'servers': []},
    {'name': 'BrasIRC', 'host': 'irc.brasirc.com.br', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://com.br/', 'servers': []},
    {'name': 'CanterNet', 'host': 'irc.canternet.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://canternet.org/', 'servers': []},
    {'name': 'Chat4all', 'host': 'irc.chat4all.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.chat4all.org/', 'servers': []},
    {'name': 'ChatSpike', 'host': 'irc.chatspike.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.chatspike.net/', 'servers': []},
    {'name': 'ChatZona', 'host': 'irc.chatzona.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://chatzona.org/', 'servers': []},
    {'name': 'CnCIRC', 'host': 'irc.cncirc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://cncirc.net/', 'servers': []},
    {'name': 'Coolsmile', 'host': 'irc.coolsmile.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://coolsmile.net/', 'servers': []},
    {'name': 'DareNET', 'host': 'irc.darenet.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.darenet.org/', 'servers': []},
    {'name': 'Dark-Tou-Net', 'host': 'irc.d-t-net.de', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://d-t-net.de/', 'servers': []},
    {'name': 'darkfasel.net', 'host': 'irc.darkfasel.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://darkfasel.net/', 'servers': []},
    {'name': 'DarkMyst', 'host': 'irc.darkmyst.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.darkmyst.org/', 'servers': []},
    {'name': 'darkscience', 'host': 'irc.darkscience.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://darkscience.net/', 'servers': []},
    {'name': 'Darkworld', 'host': 'irc.darkworld.network', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://darkworld.network/', 'servers': []},
    {'name': 'DejaToons', 'host': 'irc.dejatoons.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.dejatoons.net/', 'servers': []},
    {'name': 'DesireNET', 'host': 'irc.desirenet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://desirenet.org/', 'servers': []},
    {'name': 'ECNet', 'host': 'irc.ecnet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://ecnet.org/', 'servers': []},
    {'name': 'EpiKnet', 'host': 'irc.epiknet.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://epiknet.org/', 'servers': []},
    {'name': 'EsperNet', 'host': 'irc.esper.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.esper.net/', 'servers': []},
    {'name': 'euIRCnet', 'host': 'irc.euirc.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.euirc.net/', 'servers': []},
    {'name': 'EuropNet', 'host': 'irc.europnet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://europnet.org/', 'servers': []},
    {'name': 'Evolu.NET', 'host': 'irc.evolu.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://evolu.net/', 'servers': []},
    {'name': 'ExplosionIRC', 'host': 'irc.explosionirc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://explosionirc.net/', 'servers': []},
    {'name': 'FDFnet', 'host': 'irc.fdfnet.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://fdfnet.net/', 'servers': []},
    {'name': 'FEFnet', 'host': 'irc.fef.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://fef.net/', 'servers': []},
    {'name': 'Financialchat', 'host': 'irc.financialchat.com', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://financialchat.com/', 'servers': []},
    {'name': 'Forestnet', 'host': 'irc.forestnet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://forestnet.org/', 'servers': []},
    {'name': 'FreeUniBG', 'host': 'irc.FreeUniBG.eu', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://freeunibg.eu/', 'servers': []},
    {'name': 'GameSurge', 'host': 'irc.gamesurge.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.gamesurge.net/', 'servers': []},
    {'name': 'GeekNode', 'host': 'irc.geeknode.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.geeknode.org/', 'servers': []},
    {'name': 'GeekShed', 'host': 'irc.geekshed.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.geekshed.net/', 'servers': []},
    {'name': 'German-Elite', 'host': 'irc.german-elite.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://german-elite.net/', 'servers': []},
    {'name': 'GigaIRC', 'host': 'irc.gigairc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://gigairc.net/', 'servers': []},
    {'name': 'GIMPNet', 'host': 'irc.gimp.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.gimp.org/', 'servers': []},
    {'name': 'GlobalGamers', 'host': 'irc.globalgamers.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://globalgamers.net/', 'servers': []},
    {'name': 'GoodChatting', 'host': 'irc.goodchatting.com', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://goodchatting.com/', 'servers': []},
    {'name': 'hackint', 'host': 'irc.hackint.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://hackint.org/', 'servers': []},
    {'name': 'HybridIRC', 'host': 'irc.hybridirc.com', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://hybridirc.com/', 'servers': []},
    {'name': 'ICQ-Chat', 'host': 'irc.icq-chat.com', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://icq-chat.com/', 'servers': []},
    {'name': 'Immortal-Anime', 'host': 'irc.immortal-anime.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://immortal-anime.net/', 'servers': []},
    {'name': 'Indymedia', 'host': 'irc.indymedia.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.indymedia.org/', 'servers': []},
    {'name': 'IRC-Hispano', 'host': 'irc.irc-hispano.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.irc-hispano.org/', 'servers': []},
    {'name': 'IRC2', 'host': 'irc.irc2.hu', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://irc2.hu/', 'servers': []},
    {'name': 'IRC4Fun', 'host': 'irc.irc4fun.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://irc4fun.net/', 'servers': []},
    {'name': 'IRCGate.it', 'host': 'irc.ircgate.it', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://ircgate.it/', 'servers': []},
    {'name': 'IRCHighway', 'host': 'irc.irchighway.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.irchighway.net/', 'servers': []},
    {'name': 'IRCsource', 'host': 'irc.ircsource.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://ircsource.net/', 'servers': []},
    {'name': 'IRCtoo', 'host': 'irc.irctoo.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://irctoo.net/', 'servers': []},
    {'name': 'IRCube', 'host': 'irc.ircube.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://ircube.org/', 'servers': []},
    {'name': 'IrcWorld', 'host': 'irc.ircworld.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://ircworld.org/', 'servers': []},
    {'name': 'IRDSI', 'host': 'irc.irdsi.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://irdsi.net/', 'servers': []},
    {'name': 'KampungChat', 'host': 'irc.kampungchat.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://kampungchat.org/', 'servers': []},
    {'name': 'KnightIRC', 'host': 'irc.knightirc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://knightirc.net/', 'servers': []},
    {'name': 'Kreynet', 'host': 'irc.krey.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://krey.net/', 'servers': []},
    {'name': 'Krono', 'host': 'irc.krono.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://krono.net/', 'servers': []},
    {'name': 'LibraIRC', 'host': 'irc.librairc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.librairc.net/', 'servers': []},
    {'name': 'LichtSnel', 'host': 'irc.lichtsnel.nl', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://lichtsnel.nl/', 'servers': []},
    {'name': 'LinkNet', 'host': 'irc.link-net.be', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.link-net.org/', 'servers': []},
    {'name': 'Luatic', 'host': 'irc.luatic.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://luatic.net/', 'servers': []},
    {'name': 'Maddshark', 'host': 'irc.maddshark.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://maddshark.net/', 'servers': []},
    {'name': 'MagicStar', 'host': 'irc.magicstar.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://magicstar.net/', 'servers': []},
    {'name': 'MagNET', 'host': 'irc.perl.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.irc.perl.org/', 'servers': []},
    {'name': 'Mibbit', 'host': 'irc.mibbit.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://mibbit.net/', 'servers': []},
    {'name': 'MindForge', 'host': 'irc.mindforge.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://mindforge.org/', 'servers': []},
    {'name': 'NationCHAT', 'host': 'irc.nationchat.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://nationchat.org/', 'servers': []},
    {'name': 'NightStar', 'host': 'irc.nightstar.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://nightstar.net/', 'servers': []},
    {'name': 'NullIRC', 'host': 'irc.nullirc.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://nullirc.net/', 'servers': []},
    {'name': 'OltreIrc', 'host': 'irc.oltreirc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://oltreirc.net/', 'servers': []},
    {'name': 'OpenJoke', 'host': 'irc.openjoke.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://openjoke.org/', 'servers': []},
    {'name': 'OptiLan', 'host': 'irc.lt-tech.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://lt-tech.org/', 'servers': []},
    {'name': 'Orixon', 'host': 'irc.orixon.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.orixon.org/', 'servers': []},
    {'name': 'OzOrg', 'host': 'irc.oz.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.oz.org/', 'servers': []},
    {'name': 'P2P-NET', 'host': 'irc.p2p-network.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://p2p-network.net/', 'servers': []},
    {'name': 'PhatNET', 'host': 'irc.phat-net.de', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://phat-net.de/', 'servers': []},
    {'name': 'PIK', 'host': 'irc.krstarica.com', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.krstarica.com/', 'servers': []},
    {'name': 'PIRC', 'host': 'irc.pirc.pl', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://pirc.pl/', 'servers': []},
    {'name': 'PTnet', 'host': 'irc.ptnet.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.ptnet.org/', 'servers': []},
    {'name': 'Recycled-IRC', 'host': 'irc.recycled-irc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://recycled-irc.net/', 'servers': []},
    {'name': 'RetroNode', 'host': 'irc.retroit.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://retroit.org/', 'servers': []},
    {'name': 'Rezosup', 'host': 'irc.rezosup.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://rezosup.org/', 'servers': []},
    {'name': 'RusNet', 'host': 'irc.rusnet.org.ru', 'port': 6668, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.rusnet.org/', 'servers': []},
    {'name': 'ScaryNet', 'host': 'irc.scarynet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://scarynet.org/', 'servers': []},
    {'name': 'Serenity-IRC', 'host': 'irc.serenity-irc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://serenity-irc.net/', 'servers': []},
    {'name': 'ShadowFire', 'host': 'irc.shadowfire.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://shadowfire.org/', 'servers': []},
    {'name': 'ShadowWorld', 'host': 'irc.shadowworld.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://shadowworld.net/', 'servers': []},
    {'name': 'SimosNap', 'host': 'irc.simosnap.com', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://simosnap.com/', 'servers': []},
    {'name': 'SkyChatz', 'host': 'irc.SkyChatz.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://skychatz.org/', 'servers': []},
    {'name': 'Skyrock', 'host': 'irc.skyrock.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://skyrock.net/', 'servers': []},
    {'name': 'Slacknet', 'host': 'irc.slacknet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://slacknet.org/', 'servers': []},
    {'name': 'Slashnet', 'host': 'irc.slashnet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.slashnet.org/', 'servers': []},
    {'name': 'smurfnet', 'host': 'irc.smurfnet.ch', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://smurfnet.ch/', 'servers': []},
    {'name': 'SorceryNet', 'host': 'irc.sorcery.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.sorcery.net/', 'servers': []},
    {'name': 'SpotChat', 'host': 'irc.spotchat.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.spotchat.org/', 'servers': []},
    {'name': 'ST-City', 'host': 'irc.st-city.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://st-city.net/', 'servers': []},
    {'name': 'Starlink-irc', 'host': 'irc.starlink-irc.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://starlink-irc.org/', 'servers': []},
    {'name': 'StarLink.Org', 'host': 'irc.starlink.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://starlink.org/', 'servers': []},
    {'name': 'StayNet', 'host': 'irc.staynet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://staynet.org/', 'servers': []},
    {'name': 'StormBit', 'host': 'irc.stormbit.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.stormbit.net/', 'servers': []},
    {'name': 'synIRC', 'host': 'irc.synirc.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.synirc.net/', 'servers': []},
    {'name': 'TechNet', 'host': 'irc.technet.chat', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://technet.chat/', 'servers': []},
    {'name': 'tilde.chat', 'host': 'irc.tilde.chat', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://tilde.chat/', 'servers': []},
    {'name': 'Tweakers', 'host': 'irc.tweakers.net', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://tweakers.net/', 'servers': []},
    {'name': 'UnderMind', 'host': 'irc.undermind.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://undermind.net/', 'servers': []},
    {'name': 'WeNet', 'host': 'irc.wenet.ru', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://wenet.ru/', 'servers': []},
    {'name': 'WhatNet', 'host': 'irc.whatnet.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://whatnet.org/', 'servers': []},
    {'name': 'WixChat', 'host': 'irc.wixchat.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://wixchat.org/', 'servers': []},
    {'name': 'WorldIRC', 'host': 'irc.worldirc.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://worldirc.org/', 'servers': []},
    {'name': 'Xertion', 'host': 'irc.xertion.org', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.xertion.org/', 'servers': []},
    {'name': 'Xevion', 'host': 'irc.xevion.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://xevion.net/', 'servers': []},
    {'name': 'NewNet', 'host': 'club.newnet.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://newnet.net/', 'servers': ['tildeclub.newnet.net:6667', 'uswest.newnet.net:6667']},
    {'name': 'RelicNet', 'host': 'irc.relic.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://relic.net/', 'servers': []},
    {'name': 'amigaworld', 'host': 'irc.amigaworld.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://amigaworld.net/', 'servers': ['91.213.203.192:6667']},
    {'name': 'ScoutLink', 'host': 'webchat-ircd.scoutlink.net', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://www.scoutlink.net/', 'servers': ['clovehitch.scoutlink.net:6667', 'birch2.scoutlink.net:6667']},
    {'name': 'BlafaselNet', 'host': 'irc.blafasel.de', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://blafasel.de/', 'servers': ['space.blafasel.de:6667']},
    {'name': 'GRnet', 'host': 'rea.irc.gr', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://grnet.wordpress.com/about/grnet-servers/', 'servers': ['blue.ircn.gr:6667', 'eos.ircn.gr:6667']},
    {'name': 'UniBG', 'host': 'irc.unibg.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://unibg.org/', 'servers': ['irc.rosal.bg:6667']},
    {'name': 'Wunder-Nett', 'host': 'irc.wunder-nett.org', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://wunder-nett.org/', 'servers': []},
    {'name': 'Zeolia', 'host': 'irc.zeolia.chat', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://zeolia.chat/', 'servers': ['bds.zeolia.chat:6667', 'avalon.zeolia.chat:6667']},
    {'name': 'PureIRC', 'host': 'irc.pureirc.com', 'port': 6697, 'tls': True, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://pureirc.com/', 'servers': ['irc.pureirc.us:+6697', 'irc.sg.pureirc.us:+6697', 'irc.nl.pureirc.us:+6697']},
    {'name': 'Communiti-Chat', 'host': 'atrium.communiti.chat', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://communiti.chat/', 'servers': []},
    {'name': 'TeapotChat', 'host': 'cardamom.teapot.chat', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://teapot.chat/', 'servers': ['earlgrey.teapot.chat:6667']},
    {'name': 'WebIRC', 'host': 'webirc.chat', 'port': 6667, 'tls': False, 'nick': 'comicfan', 'username': '', 'password': '', 'channels': '', 'website': 'https://webirc.chat/', 'servers': []},
]
