cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED SOURCE_ROOT OR NOT DEFINED DESTINATION_ROOT)
    message(FATAL_ERROR "SOURCE_ROOT and DESTINATION_ROOT are required")
endif()
get_filename_component(source_root "${SOURCE_ROOT}" REALPATH)
get_filename_component(destination_root "${DESTINATION_ROOT}" ABSOLUTE)
function(reject_destination_symlinks path)
    set(current "${path}")
    while(TRUE)
        if(IS_SYMLINK "${current}")
            message(FATAL_ERROR "Runtime destination must not traverse a symlink: ${current}")
        endif()
        get_filename_component(parent "${current}" DIRECTORY)
        if(parent STREQUAL current)
            break()
        endif()
        set(current "${parent}")
    endwhile()
endfunction()
reject_destination_symlinks("${destination_root}")
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/runtime-assets.txt" approved_files)
foreach(relative IN LISTS approved_files)
    if(relative STREQUAL "" OR relative MATCHES "^#")
        continue()
    endif()
    if(IS_ABSOLUTE "${relative}" OR relative MATCHES "(^|/)\\.\\.(/|$)" OR
       NOT relative MATCHES "^((assets|themes|licenses|third_party)/|LICENSE$|THIRD_PARTY_NOTICES\\.md$)")
        message(FATAL_ERROR "Invalid runtime asset path in manifest")
    endif()
    set(source "${source_root}/${relative}")
    if(NOT EXISTS "${source}" OR IS_DIRECTORY "${source}")
        message(FATAL_ERROR "Required runtime asset is missing: ${relative}")
    endif()
    get_filename_component(actual_source "${source}" REALPATH)
    if(NOT actual_source STREQUAL source)
        message(FATAL_ERROR "Runtime asset must not be a symlink: ${relative}")
    endif()
    set(destination "${destination_root}/${relative}")
    if(IS_SYMLINK "${destination}")
        message(FATAL_ERROR "Runtime asset destination must not be a symlink: ${relative}")
    endif()
    reject_destination_symlinks("${destination}")
    get_filename_component(parent "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(COPY_FILE "${source}" "${destination}" ONLY_IF_DIFFERENT)
endforeach()
